### ISSUE TITLE
sqz cli commands throw error message

### ISSUE THREAD

**Issue by goldsteinrazvan** [SqueezerIO/squeezer#38]
Bug Report Template -----------------------------------------------

##### Squeezer Framework Version information ( `squeezer-cli version` ) :

* Squeezer CLI version: 1.1.14
* Node version: 6.11.0
* Operating system: Windows 10 Pro, version 1703, OS Build 15063.413

##### Expected Behavior:
I expect that the commands in the cli should execute without any problems, i.e: "sqz create --project my-first-project --template aws-api-nodejs --email you@example.org" should create a new project with the name "my-first-project" based on the AWS generic API Hello World template. 
##### Actual Behavior:
All sqz commands throw the same error message in the cli. The error message can be seen below: 

module.js:471
    throw err;
    ^
Error: Cannot find module 'C:\Users\Bogdan\AppData\Roaming\npm\node_modules\squeezer-cli\bin/lib/common/cli/error'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Bogdan\AppData\Roaming\npm\node_modules\squeezer-cli\bin\bin.js:10:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by nick-csu** [comment]
@goldsteinrazvan I've found the issue , it seems that is related to a path loading issue on Windows . I've attached it to a milestone https://github.com/SqueezerIO/squeezer/milestone/3

**Comment by jensneuhaus** [comment]
Squeezer looks great to me. Unfortunately I have the same error.

* Squeezer CLI version: 1.1.14
* Node version: 8.1.4
* Operating system: OS X (10.12.6.)

**Comment by nick-csu** [comment]
thanks for the update @jensneuhaus , you should see the fix on next release .

**Comment by thewtex** [comment]
Also observing this on Linux, node version 6.11.4.

**Comment by nick-csu** [comment]
thanks for feedback @thewtex ! it will be fixed on the next release , you can add a repo watch and grab the fix instantly :)

Cheers !
