### ISSUE TITLE
 Cannot find module 'aws-sdk'

### ISSUE THREAD

**Issue by KonradIT** [SqueezerIO/squeezer#57]
Bug Report Template -----------------------------------------------

##### Squeezer Framework Version information ( `squeezer-cli version` ) :

 * Squeezer CLI version: v1.1.21
 * Node version: v9.2.1
 * OS platform: linux | arch

##### Expected Behavior:

Compile

##### Actual Behavior:

    Error: Cannot find module 'aws-sdk/clients/CloudFormation'

Have aws-sdk installed.

Log here: https://linx.li/mv4a66qv.txt

**Comment by nick-csu** [comment]
hello @KonradIT  . we fixed the issue on the latest Squeezer release . could you update the CLI version to the latest and reinstall packages in the project ? Thank you !

**Comment by KonradIT** [comment]
@nickchisiu now I get:

    Error: Cannot find module './logs'

**Comment by nick-csu** [comment]
@KonradIT could you make a re-check ? thanks !

**Comment by nick-csu** [comment]
@KonradIT did the issue fixed so that we can close the issue ? Thanks !

**Comment by KonradIT** [comment]
Yes, solved!
