### ISSUE TITLE
Add sourcemap for webpack

### ISSUE THREAD

**Issue by nick-csu** [SqueezerIO/squeezer#61]
##### Feature Request:

When functions are compiled locally & deployed to the cloud is hard to debug because of the missing sourcemap implementation

##### Expected behaviour:

See the exact line where error occured

**Comment by stablexbt** [comment]
#### Source map added to webpack
* The Webpack devtools are set to generate sourcemap.
* 2/2 webpack function files were modified to add devtools functionalities.
* Errors will be displayed with line numbers of original files, hence easing down debugging.
* Devtool setting can be changed from "source-map" to "eval-source-map" for faster development and testing purposes.

Sourcemaps are generated by adding configuration to webpack exports

`devtool: 'source-map'`

"Simplest solutions are usually the correct ones."
